spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: studentModule
        uri: http://localhost:8095/
        predicates:
        - Path=/student/**
      - id: gradingModule
        uri: http://localhost:8096/
        predicates:
        - Path=/grade/**
            
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://eurekaserver2:8762/eureka



